#!/bin/sh
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Real_cls.txt --target ./txt/target_Art_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Real_cls.txt --target ./txt/target_Clipart_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Real_cls.txt --target ./txt/target_Product_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Product_cls.txt --target ./txt/target_Real_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Product_cls.txt --target ./txt/target_Art_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Product_cls.txt --target ./txt/target_Clipart_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Art_cls.txt --target ./txt/target_Clipart_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Art_cls.txt --target ./txt/target_Product_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Art_cls.txt --target ./txt/target_Real_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Clipart_cls.txt --target ./txt/target_Real_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Clipart_cls.txt --target ./txt/target_Product_cls.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_CDA.yaml --source ./txt/source_Clipart_cls.txt --target ./txt/target_Art_cls.txt --exp_name "ODA_OOD_LOGIT_END"
