#!/bin/sh
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Real_pada.txt --target ./txt/target_Art_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Real_pada.txt --target ./txt/target_Clipart_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Real_pada.txt --target ./txt/target_Product_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Product_pada.txt --target ./txt/target_Real_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Product_pada.txt --target ./txt/target_Art_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Product_pada.txt --target ./txt/target_Clipart_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Art_pada.txt --target ./txt/target_Clipart_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Art_pada.txt --target ./txt/target_Product_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Art_pada.txt --target ./txt/target_Real_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Clipart_pada.txt --target ./txt/target_Real_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Clipart_pada.txt --target ./txt/target_Product_pada.txt --exp_name "ODA_OOD_LOGIT_END"
python train_dance_nearest.py --config configs/officehome-train-config_PDA.yaml --source ./txt/source_Clipart_pada.txt --target ./txt/target_Art_pada.txt --exp_name "ODA_OOD_LOGIT_END"
